apiVersion: v1
kind: Service
metadata:
  labels:
    service: udagram-auth-api
  name: udagram-auth-api
spec:
  ports:
    - name: "8080"
      port: 8080
      targetPort: 8080
  selector:
    service: udagram-auth-api
